"""
Rsync Output Parser.
Decodes stdout streams generated by `rsync --info=progress2` to extract structured progress.
"""

import re
from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class TransferProgress:
    """Structured progress metrics parsed from rsync output."""
    bytes_transferred: int
    percentage: int
    speed_str: str
    eta_str: str
    files_transferred: Optional[int] = None
    to_check_str: Optional[str] = None


class ProgressParser:
    """
    Parses live progress updates from rsync stdout.
    Matches lines generated by `rsync --info=progress2`:
    Example format:
        78,147,968  45%   74.52MB/s    0:01:14 (xfr#412, to-chk=85/1042)
    """

    # Regex targeting: bytes, percentage, transfer-speed, ETA, (files transferred, remaining files)
    PROGRESS_PATTERN = re.compile(
        r"^\s*([\d,]+)\s+(\d+)%\s+([\d.]+[a-zA-Z]+/s)\s+([\d:]+)"
        r"(?:\s+\(xfr#(\d+),\s+(?:ir-chk|to-chk)=(\d+/\d+)\))?"
    )

    def parse_line(self, line: str) -> Optional[TransferProgress]:
        """
        Parses a single terminal update string into a TransferProgress dataclass.
        Lines often arrive delimited with `\r` rather than `\n`.
        """
        clean_line = line.strip()
        if not clean_line:
            return None

        match = self.PROGRESS_PATTERN.search(clean_line)
        if not match:
            return None

        bytes_raw, percent_raw, speed, eta, xfr_raw, to_chk = match.groups()

        try:
            bytes_transferred = int(bytes_raw.replace(",", ""))
            percentage = int(percent_raw)
            files_transferred = int(xfr_raw) if xfr_raw else None

            return TransferProgress(
                bytes_transferred=bytes_transferred,
                percentage=percentage,
                speed_str=speed,
                eta_str=eta,
                files_transferred=files_transferred,
                to_check_str=to_chk,
            )
        except ValueError:
            return None